pipeline {
  agent any
  stages {
    stage('build') {
      steps {
        sh 'chmod +x gradlew'
        sh './gradlew setupDecompWorkspace build'
      }
    }
    stage('deploy') {
      steps {
        sh 'cp build/libs/modid-1.0.jar /var/jenkins_home/minecraft-data/mods'
      }
    }
    stage('restart') {
      steps {
        sh 'docker restart cjug4kids-minecraft_minecraft_1'
      }
    }
  }
}
